### ISSUE TITLE
Tutorial on RTuinOS?

### ISSUE THREAD

**Issue by bouchtaoui-dev** [PeterVranken/RTuinOS#3]
Arduino is a very cool to learn the basics of the microcontroller world, so I thought it would be great if there's a tutorial about how RTuinOS work, to learn the principles of an RTOS. Do we have a tutorial about how to build a RTOS on Arduino?

I was thinking about the tick timer, how to handle an interrupt, how to save the complete state (registers, execution pointer, stack pointer) and fetch it back and so on...

The while-loop() is the basic form and anybody with a bit of skills know it should never leave the while(). It's like writing a simple basic application in C in the main(). But if you want to do more, the main() is just an entry-point you won't see it anymore as it's kind of hidden away. If we want to do a bit more complicated stuff, like multitasking, you just need a RTOS, So it would be nice if there's a kind of basic stuff to build a simple RTOS and maybe RTuinOS is just that :)

Ooh, I see a GettingStarted pdf document. I'll read it right away.

**Comment by PeterVranken** [comment]
Hi Andaluz,

RTuinOS itself is a bit like the tutorial you ask for. The [manual](https://sourceforge.net/projects/rtuinos/files/RTuinOS-1.0-UserGuide.pdf/download) follows a step by step concept to explain how it comes from simple loop programming to tasks and an RTOS concept. The scheduling is explained and the signaling objects for safe inter-task communication are introduced.

Secondary, if you look into the implementation - a single C source file - you will likely find it well documented, readable and transparent.

Actually, the focus in this project was mainly put on transparency and clearness. Teaching people was definitely an intend.

Note, the main repository of RTuinOS is at SourceForge, consider visiting [https://sourceforge.net/projects/rtuinos/](https://sourceforge.net/projects/rtuinos/).
